[target.aarch64-unknown-linux-gnu]
ar = "aarch64-unknown-linux-gnu-ar"
linker = "aarch64-unknown-linux-gnu-gcc"

[target.armv7-unknown-linux-gnueabihf]
ar = "armv7-unknown-linux-gnueabihf-ar"
linker = "armv7-unknown-linux-gnueabihf-gcc"

[target.x86_64-unknown-linux-gnu]
ar = "x86_64-unknown-linux-gnu-ar"
linker = "x86_64-unknown-linux-gnu-gcc"

[target.x86_64-pc-windows-gnu]
ar = "x86_64-w64-mingw32-ar"
linker = "x86_64-w64-mingw32-gcc"
